### ISSUE TITLE
multi threading

### ISSUE THREAD

**Issue by sbombin** [ingmbioinfo/combiroc#2]
Hello,

Thank you for the great package! Does CombiRoc support multi threading?

**Comment by ricrossi** [comment]
hello @sbombin, 
appreciated your comment! We just released an important CRAN-ready release of the package (v.0.3.4) with some new features; alas, we did not address (yet) multi threading support, even if I do agree it would be beneficial for easier computation when optimizing big signarures (i.e. >20 markers).
